#!/bin/bash

# git-open - open remote web site with browser

# Usage: git open [remote] (aliased in ~/.gitconfig)
#        git-open [remote] (directly use this script)

REMOTE=${1:-origin}

# function usage() {
#   echo "git-open - open remote web site with browser"
#   echo ""
#   echo "Usage: git open [remote] (aliased in ~/.gitconfig)"
#   echo "       git-open [remote] (directly use this script)"
# }

function variable_open() {
  case ${OSTYPE} in
    darwin* )
      open "$1"
      ;;
    linux* )
      xdg-open "$1"
      ;;
    cygwin* )
      cygstart "$1"
      ;;
  esac
}

function error {
  echo -e "\033[31mfatal\033[m" "$*"
}

function check_remote() {
  git remote -v | grep "$REMOTE" >/dev/null || {
    error "Remote \"$REMOTE\" not found, exitting."
    exit 1
  }
}

function encode_to_html() {
  local repo="$(echo $url | awk -F: '{ print $2 }')"
  encoded="https://github.com/$repo"
}

function extract_url() {
  url="$(git remote -v | grep "$REMOTE" | awk '{print $2}' | uniq )"
  case "$url" in
    git@* )
      encode_to_html
      url="$encoded"
      ;;
    https* )
      :
      ;;
    * )
      error "URL format invalid"
      echo "===> $url"
      exit 2
      ;;
  esac
}

check_remote
extract_url
variable_open "$url"
